# Generated by Django 5.0.6 on 2024-05-16 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='terminado',
            field=models.BooleanField(default=False),
        ),
    ]
